    - name: Join the ZeroTier network using shell
        ansible.builtin.shell:
          cmd: /usr/local/bin/zerotier-cli join 50eee35c5523044f
        become: true
        register: zerotier_join_output
        changed_when: zerotier_join_output.rc == 0 and "join OK" in zerotier_join_output.stdout
