----
- name: Install Nala package manager
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Ensure apt cache is up to date
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install nala
      ansible.builtin.apt:
        name: nala
        state: present
