---
- name: Update and upgrade Ubuntu servers
  hosts: all
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: Update apt cache
      nala:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      nala:
        upgrade: dist

    - name: Remove unused packages
      nala:
        autoremove: yes
        purge: yes

    - name: Clean apt cache
      nala:
        autoclean: yes
