---
- name: Update and upgrade Ubuntu hosts
  hosts: all
  become: true 
  become_method: sudo
  
  tasks:
  - name: Wait for apt lock to be released
      apt:
        update_cache: yes
        cache_valid_time: 3600
        lock_timeout: 600
        
  - name: Update APT package cache
    apt: 
      update_cache: yes
  
  - name: Upgrade all packages
    apt: 
      upgrade: yes 
      state: latest 
    
  - name:  Clean up APT cache (optional)
    apt: 
      autoremove: yes
      clean: yes 
