---
- name: Update Windows computers
  hosts: windows
  gather_facts: no

  tasks:
    - name: Install Windows updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
        reboot_timeout: 3600
      register: update_result

    - name: Show update results
      debug:
        var: update_result
