---
- name: Install and start ZeroTier
  hosts: all
  become: true
  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Install ZeroTier using official install script
      shell: |
        curl -s https://install.zerotier.com | bash
      args:
        creates: /usr/sbin/zerotier-cli

    - name: Enable and start ZeroTier service
      systemd:
        name: zerotier-one
        enabled: yes
        state: started

    - name: Verify ZeroTier installation
      command: zerotier-cli status
      register: zerotier_status
      changed_when: false

   - name: Show ZeroTier status
      debug:
        msg: "{{ zerotier_status.stdout }}"
